# Generated by Django 4.2.3 on 2024-07-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantuty',
            new_name='quantity',
        ),
    ]
